### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShopCorp/tests_base_framework#24]
- [x] Bump Version to 2.1.0 : #28 
- [x]  Workflow and paths : #22
- [x] Update Dependencies : #23
- [x] Automate Release and Tagging : #27 #30 #32

**Comment by boubkerbribri** [comment]
Still getting the wrong tag
